### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by AkiraVoid** [AkiraVoid-Productions/Hookdown#2]
The 1.0.0 of hookdown will have these features:

- [x] AkiraVoid-Productions/Hookdown-b#3 
- [x] AkiraVoid-Productions/Hookdown-b#1 
- [x] AkiraVoid-Productions/Hookdown-b#4 

It will be released as soon as these features are done. 

Before release, check:

- [x] License included.
- [x] Code of conduct added.
- [x] Readme edited.
- [x] package.json `repository`, `version`, etc. have been set.
